fix: Use settings attribute for Redis maxmemory options
Redis NixOS module requires maxmemory* options to be in settings{} block.

Error: The option `services.redis.servers.nakamura.maxmemory' does not exist